---
  - name: create /etc/docker directory
    file:
      path: /etc/docker
      state: directory

  - name: write docker config file
    template:
      src: daemon.json
      dest: /etc/docker/daemon.json

  # start and verify that Docker installed succesfully and is running
  - name: start docker service
    service:
      name: docker
      state: started
      enabled: yes
    when: force_docker_restart is not defined or force_docker_restart|bool == false # only run if not going to restart right after

  - name: restart docker service because we ALWAYS want daemon.json
    service:
      name: docker
      state: restarted
      enabled: yes

  # force_kubelet_restart=true to force restart
  # on install, service will be started with the task before this
  # on upgrade, this will be restarted only of the package was upgraded
  - name: restart docker service
    service:
      name: docker
      state: restarted
      enabled: yes
    when: >
      (force_docker_restart is defined and force_docker_restart|bool == true) or
      ((upgrading is defined and upgrading|bool == true) and
      (allow_package_installation|bool == false or
      ((docker_installation_rpm is defined and docker_installation_rpm.changed == true) or
      (docker_installation_deb is defined and docker_installation_deb.changed == true))))

  - name: verify docker is running
    command: docker ps
